### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by maxkoshevoi** [maxkoshevoi/NureTimetable#16]

**Comment by maxkoshevoi** [comment]
Some resources:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/theming
https://developer.android.com/preview/features/darktheme#supporting_dark_theme_in_your_app
https://stackoverflow.com/questions/42997914/xamarin-forms-switching-between-dark-light-themes-at-run-time

**Comment by Felkree** [comment]
I think this function should be, since so many programmers like and use dark themes.
