### ISSUE TITLE
Autoupdate timetable

### ISSUE THREAD

**Issue by maxkoshevoi** [maxkoshevoi/NureTimetable#22]
This could be a useful feature (especially in combination with #18), but I don't want to overload [cist](http://cist.nure.ua) with several thousand simultaneous queries. 

Proposed solution: Only one (selected) timetable will be updated at random time between 6 and 8 am

**Comment by Felkree** [comment]
I support this proposal.

**Comment by udv-code** [comment]
It can be done with services)
Maybe I can help?

**Comment by udv-code** [comment]
Also you can make a little server that makes request from cist once a day.
And now android apps need to just request server to give that info.
No overloading.

**Comment by maxkoshevoi** [comment]
> Also you can make a little server that makes request from cist once a day.
> And now android apps need to just request server to give that info.
> No overloading.

1) This once a day full timetable load will be hard on cost (cist api because locked exactly because people started downloading timetable for everything once a day)
2) Timetable updates at different time each day  and there is no way to know when it happens (it can be 5-7 AM)
3) This approach will require to host servers somewhere, which is not free (especially in the long term)

**Comment by maxkoshevoi** [comment]
> It can be done with services)
> Maybe I can help?

Sure! Any help is appreciated

**Comment by udv-code** [comment]
> > Also you can make a little server that makes request from cist once a day.
> > And now android apps need to just request server to give that info.
> > No overloading.
> 
> 1. This once a day full timetable load will be hard on cost (cist api because locked exactly because people started downloading timetable for everything once a day)
> 2. Timetable updates at different time each day  and there is no way to know when it happens (it can be 5-7 AM)
> 3. This approach will require to host servers somewhere, which is not free (especially in the long term)

Ok that seems pretty reasonable.

**Comment by maxkoshevoi** [comment]
Implemented it in more straightforward way.
- App already forbids updating timetable more than once a day
- When user opens an app, it tries to update selected timetables (does nothing if timetable was already updated today)
- When user switches selected timetable and opens timetable page, app tries to update newly selected timetable (does nothing if timetable was already updated today)

This way, for someone looking at any timetable, it will always be up-to-date (assuming user has internet connection).

Closing issue for now. Can be reopened later If there will be a justifiable need for automatically updating timetable while app is closed.
