### ISSUE TITLE
Crash on opening settings of already saved timetable

### ISSUE THREAD

**Issue by Kugumin** [maxkoshevoi/NureTimetable#37]
So, issue title says for the issue itself. 

Device: Xiaomi Mi 9T Pro
ROM/OS: MiRoom 9.12.27 on Android 10
App version: 1.6.1823

Screenshot with crashlog:
![Screenshot_2020-01-05-13-24-21-782_com miui bugreport](https://user-images.githubusercontent.com/42800753/71779385-d6aa5400-2fbe-11ea-8e90-eb7ef98b5aee.png)

**Comment by maxkoshevoi** [comment]
Its known bug on latest beta version. For some reason build doesn't include popup class, so application crashes whenever it tries to display an alert popup or one with action list. I'm currently working on it.

**Comment by maxkoshevoi** [comment]
Fix in version 1.6.1845
