### ISSUE TITLE
View time until break

### ISSUE THREAD

**Issue by undeadspez** [maxkoshevoi/NureTimetable#5]
Add feature that lets users to view time until break. It may look like this:

![image](https://user-images.githubusercontent.com/32403828/53053898-66c8d300-34ab-11e9-9cdf-03ba8e45c7f4.png)

**Comment by maxkoshevoi** [comment]
Done. Thanks a lot for design idea!
![image](https://user-images.githubusercontent.com/6609929/53206999-3152ef80-363b-11e9-96be-ac2932f81c4f.png)
