### ISSUE TITLE
Date dublication bug

### ISSUE THREAD

**Issue by Alexander-Degtyar** [maxkoshevoi/NureTimetable#8]
Dates are duplicated next week. [nuretimetable](https://user-images.githubusercontent.com/38611695/53299199-ee159e00-383f-11e9-92a8-a6c0a37cb2a6.gif)

**Comment by maxkoshevoi** [comment]
Hi, this bug is fixed in version 1.3.440. 
What version are you using? You can check it in "About app" section of the application

**Comment by Alexander-Degtyar** [comment]
> Hi, this bug is fixed in version 1.3.440.
> What version are you using? You can check it in "About app" section of the application

Oh. You are right. Update fixes it. Thanks.
